[package]
name = "backtester"
version = "0.1.0"
authors = ["Sebastian Rollen <seb@overmu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
async-trait = "0.1.51"
bdays = "0.1.2"
chrono = "0.4.19"
futures = "0.3.15"
polygon = { git = "ssh://git@github.com/Overmuse/polygon", tag = "v0.11.2", default-features = false, features = ["rest"], optional=true }
serde = "1.0.130"
serde_json = "1.0.68"
tokio = "1.6.0"

[features]
default = []
