[package]
name = "polygon"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
backtester = { path = "../..", features = ["polygon"] }
chrono = "0.4"
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
